apiVersion: v1
kind: Service
metadata:
  name: service-registry-service
  labels:
    name: service-registry-service
    app: banking-system
spec:
  selector:
    name: service-registry-deploy
    app: banking-system
  ports:
    - protocol: "TCP"
      port: 8085
      targetPort: 8085
      nodePort: 30004
  type: NodePort