apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: prithwi8972/bank-service-registry:1.0
    ports:
      - containerPort: 8085
    resources:
      limits:
        memory: "1200Mi"
      requests:
        memory: "600Mi"

